export enum EMPLOYEE_ACTIONS {
  SET_EMPLOYEES = 'SET_EMPLOYEES',
  ADD_EMPLOYEE = 'ADD_EMPLOYEE',
  GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST',
  GET_EMPLOYEE_ERROR = 'GET_EMPLOYEE_ERROR',
  SET_EMPLOYEE_LOADING = 'SET_EMPLOYEE_LOADING',
}
